# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf168c5cf34bf0b8dcd5319d54965aed"
name = "PD Builder"
application_url = "https://example.com/"
embedded = true
handle = "pd-builder"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
